DM_TITLE:Visualizador
DM_PX_SHARP:Pixel perfecto
DM_EU_SHARP:Europeo 4:3
DM_US_SHARP:Norteamericano 4:3
DM_PX_CRT:Pixel perfecto CRT
DM_EU_CRT:Europeo 4:3 CRT
DM_US_CRT:Norteamericano 4:3 CRT

LM_TITLE:Idioma

IG_PAUSE:Pausa
IG_LOADSAVE:Guardar/cargar juego
IG_KEYBOARD:Teclado virtual
IG_EXIT:Salir del juego

GS_AUTHOR:Autor
GS_MUSICIAN:Compositor
GS_GENRE:Género
GS_YEAR:Año

GR_SHOOT:Dispárales
GR_PUZZLE:Puzle
GR_SPORT:Deporte
GR_ADVENTURE:Aventura
GR_PLATFORM:Plataforma
GR_MAZE:Laberinto
GR_DRIVING:Carreras
GR_PROGRAMMING:Programación

LS_TITLE:Juegos guardados

IP_TITLE:Avisos legales
IP_NOTICES:Avisos de propiedad intelectual
IP_LEGAL:Licencias

SF_SHUTDOWN:Apagando...
SF_REBOOTING:Reiniciando...

SM_TITLE:Sistema
SM_KEYBOARD:Teclado USB ›
SM_IPNOTICE:Avisos legales ›
SM_SYSTEM:Información del sistema ›
SM_FACTORY_RST:Restauración de fábrica ›

KM_TITLE:Teclado USB
KM_UK:Inglés RU
KM_US:Inglés USA
KM_DE:Alemán
KM_ES:Español
KM_FR:Francés
KM_IT:Italiano

FR_TITLE:Restauración de fábrica
FR_STATEMENT:Borrará todos los juegos y configuraciones guardadas. ¿Desea continuar?
FR_CANCEL:Cancelar
FR_CONFIRM:Restaurar

SI_TITLE:Información del sistema
SI_BUILD:Versión
SI_DATE:Fecha de la versión
SI_UPGRADE_FOUND:Actualización del firmware encontrada
SI_UPGRADE_NOT_FOUND:Actualización del firmware no encontrada
SI_NEW_FIRMWARE:¿Desea actualizar este firmware?
SI_CANCEL:Cerrar
SI_TRY_AGAIN:Buscar actualizaciones
SI_UPGRADE:Aplicar actualizaciones
