DM_TITLE:Display
DM_PX_SHARP:Pixel perfect
DM_EU_SHARP:European 4:3
DM_US_SHARP:North American 4:3
DM_PX_CRT:Pixel perfect CRT
DM_EU_CRT:European 4:3 CRT
DM_US_CRT:North American 4:3 CRT

LM_TITLE:Language

IG_PAUSE:Pause
IG_LOADSAVE:Save/load game
IG_KEYBOARD:Virtual keyboard
IG_EXIT:Exit game

GS_AUTHOR:Author
GS_MUSICIAN:Composer
GS_GENRE:Genre
GS_YEAR:Year

GR_SHOOT:Shoot 'em up
GR_PUZZLE:Puzzle
GR_SPORT:Sport
GR_ADVENTURE:Adventure
GR_PLATFORM:Platform
GR_MAZE:Maze
GR_DRIVING:Driving
GR_PROGRAMMING:Programming

LS_TITLE:Saved games

IP_TITLE:Legal notices
IP_NOTICES:IP notices
IP_LEGAL:Licenses

SF_SHUTDOWN:Shutting down...
SF_REBOOTING:Restarting...

SM_TITLE:System
SM_KEYBOARD:USB keyboard ›
SM_IPNOTICE:Legal notices ›
SM_SYSTEM:System information ›
SM_FACTORY_RST:Factory reset ›

KM_TITLE:USB keyboard
KM_UK:UK
KM_US:US
KM_DE:German
KM_ES:Spanish
KM_FR:French
KM_IT:Italian

FR_TITLE:Factory reset
FR_STATEMENT:This will erase all saved games and settings. Are you sure?
FR_CANCEL:Cancel
FR_CONFIRM:Reset

SI_TITLE:System information
SI_BUILD:Build
SI_DATE:Build date
SI_UPGRADE_FOUND:Firmware update found
SI_UPGRADE_NOT_FOUND:No firmware update found
SI_NEW_FIRMWARE:Do you wish to upgrade to this firmware?
SI_CANCEL:Close
SI_TRY_AGAIN:Check for update
SI_UPGRADE:Apply update

TM_TITLE:Factory test mode
TM_STATEMENT:System running - Select 'Finish' to reset console to initial customer state, left and right to test joystick (USB) ports.
TM_PING:Nothing
TM_CONFIRM:Finish
