DM_TITLE:Affichage
DM_PX_SHARP:Pixel perfect
DM_EU_SHARP:4:3 Européen
DM_US_SHARP:4:3 Nord Américain
DM_PX_CRT:CRT pixel perfect
DM_EU_CRT:4:3 CRT Européen
DM_US_CRT:4:3 CRT Nord Américain

LM_TITLE:Langue

IG_PAUSE:Pause
IG_LOADSAVE:Sauvegarder/Charger une partie
IG_KEYBOARD:Clavier virtuel
IG_EXIT:Quitter le jeu

GS_AUTHOR:Auteur
GS_MUSICIAN:Compositeur
GS_GENRE:Genre
GS_YEAR:Année

GR_SHOOT:Shoot 'em up
GR_PUZZLE:Puzzle
GR_SPORT:Sport
GR_ADVENTURE:Aventure
GR_PLATFORM:Plateforme
GR_MAZE:Labyrinthe
GR_DRIVING:Course
GR_PROGRAMMING:Programmation

LS_TITLE:Parties sauvegardées

IP_TITLE:Mentions légales
IP_NOTICES:Mentions IP
IP_LEGAL:Droits

SF_SHUTDOWN:Arrêt en cours...
SF_REBOOTING:Redémarrage en cours...

SM_TITLE:Système
SM_KEYBOARD:Clavier USB ›
SM_IPNOTICE:Mentions légales ›
SM_SYSTEM:Informations du système ›
SM_FACTORY_RST:Réinitialisation ›

KM_TITLE:Clavier USB
KM_UK:RU
KM_US:US
KM_DE:Allemand
KM_ES:Espagnol
KM_FR:Français
KM_IT:Italien

FR_TITLE:Réinitialisation
FR_STATEMENT:Cette action supprimera vos paramètres et vos parties sauvegardées. Voulez-vous continuer ?
FR_CANCEL:Quitter
FR_CONFIRM:Réinitialiser

SI_TITLE:Informations du système
SI_BUILD:Réalisation
SI_DATE:Date de réalisation
SI_UPGRADE_FOUND:Mise-à-jour du microprogramme disponible
SI_UPGRADE_NOT_FOUND:Pas de mise-à-jour du microprogramme disponible
SI_NEW_FIRMWARE:Souhaitez-vous mettre à jour le microprogramme ?
SI_CANCEL:Fermer
SI_TRY_AGAIN:Vérifier les mises-à-jour
SI_UPGRADE:Mettre à jour
