DM_TITLE:Anzeige
DM_PX_SHARP:Optimale Pixelauflösung
DM_EU_SHARP:Europa 4:3
DM_US_SHARP:Nordamerika 4:3
DM_PX_CRT:Optimale Pixelauflösung CRT
DM_EU_CRT:Europa 4:3 CRT
DM_US_CRT:Nordamerika 4:3 CRT

LM_TITLE:Sprache

IG_PAUSE:Pause
IG_LOADSAVE:Spiel speichern/laden
IG_KEYBOARD:Virtuelle Tastatur
IG_EXIT:Spiel verlassen

GS_AUTHOR:Autor
GS_MUSICIAN:Komponist
GS_GENRE:Genre
GS_YEAR:Jahr

GR_SHOOT:Shoot 'em up
GR_PUZZLE:Rätsel
GR_SPORT:Sport
GR_ADVENTURE:Abenteuer
GR_PLATFORM:Plattform
GR_MAZE:Labyrinth
GR_DRIVING:Rennen
GR_PROGRAMMING:Programmierung

LS_TITLE:Gespeicherte Spiele

IP_TITLE:Rechtliche Hinweise
IP_NOTICES:IP Hinweise
IP_LEGAL:Lizenzen

SF_SHUTDOWN:Herunterfahren...
SF_REBOOTING:Neustart...

SM_TITLE:System
SM_KEYBOARD:USB Tastatur ›
SM_IPNOTICE:Rechtliche Hinweise ›
SM_SYSTEM:Systeminformationen ›
SM_FACTORY_RST:Auf Werkseinstellung zurücksetzen ›

KM_TITLE:USB Tastatur
KM_UK:Großbritannien
KM_US:USA
KM_DE:Deutschland
KM_ES:Spanien
KM_FR:Frankreich
KM_IT:Italien

FR_TITLE:Auf Werkseinstellung zurücksetzen
FR_STATEMENT:Dies löscht alle gespeicherten Spiele und Einstellungen. Sind Sie sich sicher?
FR_CANCEL:Abbrechen
FR_CONFIRM:Zurücksetzen

SI_TITLE:Systeminformationen
SI_BUILD:Version
SI_DATE:Versionsdatum
SI_UPGRADE_FOUND:Firmware-Aktualisierung gefunden
SI_UPGRADE_NOT_FOUND:Keine Firmware-Aktualisierung gefunden
SI_NEW_FIRMWARE:Möchten Sie die Firmware installieren?
SI_CANCEL:Schließen
SI_TRY_AGAIN:Nach Aktualisierungen suchen
SI_UPGRADE:Aktualisierung anwenden
