DM_TITLE:Schermo
DM_PX_SHARP:Pixel perfect
DM_EU_SHARP:Europeo 4:3
DM_US_SHARP:Americano 4:3
DM_PX_CRT:CRT Pixel perfect
DM_EU_CRT:CRT Europeo 4:3
DM_US_CRT:CRT Americano 4:3

LM_TITLE:Lingua

IG_PAUSE:Pausa
IG_LOADSAVE:Salva/Carica partita
IG_KEYBOARD:Tastiera virtuale
IG_EXIT:Esci dal gioco

GS_AUTHOR:Autore
GS_MUSICIAN:Compositore
GS_GENRE:Genere
GS_YEAR:Anno

GR_SHOOT:Sparatutto
GR_PUZZLE:Puzzle
GR_SPORT:Sport
GR_ADVENTURE:Avventura
GR_PLATFORM:Piattaforma
GR_MAZE:Labirinto
GR_DRIVING:Automobilismo
GR_PROGRAMMING:Programmazione

LS_TITLE:Partite salvate

IP_TITLE:Note legali
IP_NOTICES:Note su IP
IP_LEGAL:Licenze

SF_SHUTDOWN:Spegnimento...
SF_REBOOTING:Ripresa gioco...

SM_TITLE:Sistema
SM_KEYBOARD:Tastiera USB ›
SM_IPNOTICE:Note legali ›
SM_SYSTEM:Informazioni di sistema ›
SM_FACTORY_RST:Ripristino impostazioni originali ›

KM_TITLE:Tastiera USB
KM_UK:UK
KM_US:USA
KM_DE:Tedesco
KM_ES:Spagnolo
KM_FR:Francese
KM_IT:Italiano

FR_TITLE:Ripristino impostazioni originali
FR_STATEMENT:Impostazioni e partite salvate verranno eliminate. Sei sicuro?
FR_CANCEL:Cancella
FR_CONFIRM:Ripristina

SI_TITLE:Informazioni di sistema
SI_BUILD:Struttura
SI_DATE:Data di sviluppo
SI_UPGRADE_FOUND:Aggiornamento del firmware trovato
SI_UPGRADE_NOT_FOUND:Aggiornamento del firmware non trovato
SI_NEW_FIRMWARE:Vuoi fare l'upgrade del firmware?
SI_CANCEL:Chiudi
SI_TRY_AGAIN:Cerca aggiornamenti
SI_UPGRADE:Applica aggiornamenti
